name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Essencial: Baixar o código do repositório para o runner
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }} # Verifique se o nome da secret está correto

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2. Build e Teste apontando para o caminho correto
      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          context: ./sensor-arduino-api
          file: sensor-arduino-api/sensor-api/docker/Dockerfile
          target: test
          load: true

      # 3. Build e Push com multi-plataforma
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./sensor-arduino-api
          file: sensor-arduino-api/sensor-api/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          target: test
          load: true
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
