name: ci

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready -U postgres
          --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run tests on runner
        run: ./mvnw test -B
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: 123

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # 1. Essencial: Baixar o código do repositório para o runner
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        if: ${{ secrets.DOCKERHUB_TOKEN != '' && vars.DOCKER_USERNAME != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Verifique se o nome da secret está correto

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2. Build e Teste apontando para o caminho correto
      - name: Run tests with Maven
        run: ./mvnw test

      # 3. Build e Push com multi-plataforma
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./sensor-api
          file: ./sensor-api/docker/Dockerfile
          build-args: |
            TESTCONTAINERS_DISABLED=1
          platforms: linux/amd64,linux/arm64
          target: test
          load: true
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
